apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  clusterIP: None
  selector:
    app: app
  type: ClusterIP
  ports:
    - port: 9000
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: app
        ports:
          - containerPort: 9000

