version: '3.7'

volumes:
    database: ~

services:
    app:
        build:
            context: .
            target: dev
            dockerfile: .docker/app/Dockerfile
        user: www-data
        volumes:
            - ./:/var/www/application:delegated
        depends_on:
            - mysql

    nginx:
        image: nginx:1.19-alpine
        depends_on:
            - app
        volumes:
            - .docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
            - ./public:/var/www/application/public
        ports:
            - "8000:80"

    mysql:
        ports:
            - "13306:3306"
